# Generated by Django 4.2.3 on 2023-07-21 13:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visitor_name', models.CharField(max_length=255, null=True)),
                ('visitor_email', models.EmailField(max_length=254)),
                ('visitor_nric', models.CharField(max_length=20, null=True)),
                ('visitor_phone', models.CharField(max_length=20, null=True)),
                ('is_preregistered', models.BooleanField(default=False)),
                ('in_time', models.TimeField(null=True)),
                ('out_time', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('purpose', models.CharField(max_length=50)),
                ('venue', models.TextField()),
                ('test', models.BooleanField(default=False)),
            ],
        ),
    ]
