# Generated by Django 4.2.3 on 2023-07-26 12:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_meeting_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
